### ISSUE TITLE
Zoom and Crosshairs

### ISSUE THREAD

**Issue by chimz76** [wootguy/weapon_custom#5]
First of all I gotta say I'm loving this! Being able to create custom weapons for my maps was a dream that had died long ago, but has been revived with this. And I've been having fun creating different weapons.
I must commend you on making such an accessible and great tool! Thank you!

Now, I've got 2 issues:

1. When I add "Zoom" to a weapon's secondary function, it bugs out. Whenever I press RMB, it Zooms and Un-Zooms instantly. Doesn't matter if I tap the button or hold it. I haven't created any Entities for it. I've just set it in the Weapon_Custom entity alone.

2. For some weapons, crosshairs don't appear. I can't find the setting for it, so I wanted to ask where I can choose the Crosshair, and if possible, where can I add my own sprite for it?

**Comment by wootguy** [comment]
1. Try copying the sniper rifle in the sample map and editing that instead. The zooming works there. If it keeps bugging then send the bsp and I can troubleshoot.
2. Crosshairs are loaded from text file configs. In the example map, the `weapon_custom_sniper` weapon has a config found at `/sprites/weapon_custom/weapon_custom_sniper.txt`. That path is combination of the `HUD Sprite Info Folder` setting in the `weapon_custom` entity and the classname of the weapon. You can change which sprite is used in the text file. If it's a custom sprite, then also update the `HUD Sprite` setting in `weapon_custom` so that the sprite is precached.

**Comment by chimz76** [comment]
Thank you for the quick answer!
The Sprite part worked perfectly.

And as for the Zoom problem, after a LOT of testing back and forth with my weapon and your sample weapons, I understood the problem.
I had not set the Primary Alternative Fire for my gun. Without it, the Zoom/Unzoom will be applied constantly when pressing or holding RMB.
After I made a copy of my Primary Fire entity, named it the alt version and added it to my gun's Primary Alt Slot, everything worked great! No more problem!

Again, thank you!

**Comment by chimz76** [comment]
Thank you for the quick answer!
The Sprite part worked perfectly.

And as for the Zoom problem, after a LOT of testing back and forth with my weapon and your sample weapons, I understood the problem.
I had not set the Primary Alternative Fire for my gun. Without it, the Zoom/Unzoom will be applied constantly when pressing or holding RMB.
After I made a copy of my Primary Fire entity, named it the alt version and added it to my gun's Primary Alt Slot, everything worked great! No more problem!

Again, thank you!
